### ISSUE TITLE
Release ZIP file includes a .git directory

### ISSUE THREAD

**Issue by jlfranklin** [backdrop-contrib/hook_post_action#2]
When unpacking the package, a git directory pointing to the maintainers private fork is created.  The release should be updated or a new release cut without the `.git` directory.

```
$ unzip -q hook_post_action.zip 
$ ls -a1 hook_post_action
.
..
.git
hook_post_action.api.php
hook_post_action_example
hook_post_action.info
hook_post_action.module
LICENSE.txt
README.md
```

**Comment by rositis** [comment]
Errant .git file has been removed from the ZIP package and new version released.
